# 张量的创建与运算

In [1]:
import torch

## 初始化张量
### 通过列表创建张量

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data.dtype

torch.int64

### 通过numpy数组创建张量

In [3]:
import numpy as np
a = np.random.normal(0, 1, 3)
a = np.array([1., 2., 3.])
b = torch.tensor(a)
b

tensor([1., 2., 3.], dtype=torch.float64)

In [4]:
c = torch.ones_like(b)
d = torch.zeros_like(b)
e = torch.rand_like(b)
e

tensor([0.7425, 0.4216, 0.0456], dtype=torch.float64)

### 随机生成某种大小张量

In [5]:
torch.rand([2, 2])
torch.rand((2, 2))

tensor([[0.6830, 0.7151],
        [0.7480, 0.6488]])

## tensor的属性

In [6]:
e.dtype
e.shape
e.device

device(type='cpu')

## tensor中的操作

### 将张量转移到gpu

In [7]:
if torch.cuda.is_available():
    e = e.to('cuda')

In [8]:
torch.is_tensor(e) # 返回bool是否是一个tensor

True

In [9]:
torch.is_complex(e) # 返回bool是否是复数类型

False

In [10]:
a = torch.tensor(0.)
torch.is_nonzero(a) # 对于单一张量返回其是否为非0

False

In [11]:
a = torch.tensor([1, 2, 3, 4, 5 ])
torch.numel(a) # 返回元素个数

5

In [12]:
torch.zeros((2, 3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [13]:
torch.zeros([2, 2], dtype=torch.double)

tensor([[0., 0.],
        [0., 0.]], dtype=torch.float64)

In [14]:
torch.arange(0, 6, 2)

tensor([0, 2, 4])

In [15]:
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [16]:
torch.range(0,5)

C:\Users\Sevent\AppData\Local\Temp/ipykernel_17584/1393396694.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,5)


tensor([0., 1., 2., 3., 4., 5.])

In [17]:
torch.linspace(4, 5, 100)

tensor([4.0000, 4.0101, 4.0202, 4.0303, 4.0404, 4.0505, 4.0606, 4.0707, 4.0808,
        4.0909, 4.1010, 4.1111, 4.1212, 4.1313, 4.1414, 4.1515, 4.1616, 4.1717,
        4.1818, 4.1919, 4.2020, 4.2121, 4.2222, 4.2323, 4.2424, 4.2525, 4.2626,
        4.2727, 4.2828, 4.2929, 4.3030, 4.3131, 4.3232, 4.3333, 4.3434, 4.3535,
        4.3636, 4.3737, 4.3838, 4.3939, 4.4040, 4.4141, 4.4242, 4.4343, 4.4444,
        4.4545, 4.4646, 4.4747, 4.4848, 4.4949, 4.5051, 4.5152, 4.5253, 4.5354,
        4.5455, 4.5556, 4.5657, 4.5758, 4.5859, 4.5960, 4.6061, 4.6162, 4.6263,
        4.6364, 4.6465, 4.6566, 4.6667, 4.6768, 4.6869, 4.6970, 4.7071, 4.7172,
        4.7273, 4.7374, 4.7475, 4.7576, 4.7677, 4.7778, 4.7879, 4.7980, 4.8081,
        4.8182, 4.8283, 4.8384, 4.8485, 4.8586, 4.8687, 4.8788, 4.8889, 4.8990,
        4.9091, 4.9192, 4.9293, 4.9394, 4.9495, 4.9596, 4.9697, 4.9798, 4.9899,
        5.0000])

In [18]:
torch.full([2, 3], 5)

tensor([[5, 5, 5],
        [5, 5, 5]])

### tensor连接

In [19]:
a = torch.rand(2,2)
b = torch.rand(2,3)
torch.cat([a, b], dim=1)

tensor([[0.1050, 0.0224, 0.1783, 0.3902, 0.8010],
        [0.1913, 0.8945, 0.7959, 0.4581, 0.5676]])

In [20]:
b = torch.rand(3, 2)
c, d=torch.chunk(b, chunks=2) # 张量分割
c.shape
d.shape
torch.chunk(b, chunks=2, dim=1)

(tensor([[0.3628],
         [0.1219],
         [0.1416]]),
 tensor([[0.2590],
         [0.6950],
         [0.9004]]))

In [21]:
t = torch.tensor([[1, 2], [3, 4]])
torch.gather(t, 1, torch.tensor([[0, 0],[1, 0]]))

tensor([[1, 1],
        [4, 3]])

In [22]:
a = torch.rand([3,4])
b = torch.reshape(a,(1, -1))

In [23]:
b

tensor([[0.6460, 0.4344, 0.5862, 0.4906, 0.2030, 0.8785, 0.9684, 0.4109, 0.5211,
         0.3615, 0.9054, 0.2046]])

In [24]:
b = torch.reshape(b, [3, 4])

In [25]:
torch.split(a, 2) # 分割tensor，传入每份的大小，chunk中传入分成几份

(tensor([[0.6460, 0.4344, 0.5862, 0.4906],
         [0.2030, 0.8785, 0.9684, 0.4109]]),
 tensor([[0.5211, 0.3615, 0.9054, 0.2046]]))

In [26]:
a = torch.rand([3, 2])
torch.squeeze(torch.reshape(a, [3, 1, 2]), dim=1)

tensor([[0.7756, 0.8545],
        [0.1971, 0.9599],
        [0.2225, 0.9425]])

In [27]:
a = torch.rand([3, 2])
b = torch.rand([3, 2])
torch.stack((a, b)) # 在新的维度对多个张量进行连接

tensor([[[0.1010, 0.7094],
         [0.3671, 0.1164],
         [0.5290, 0.1149]],

        [[0.5476, 0.3017],
         [0.8299, 0.0940],
         [0.3981, 0.9152]]])

In [28]:
torch.stack((a,b),dim=1)

tensor([[[0.1010, 0.7094],
         [0.5476, 0.3017]],

        [[0.3671, 0.1164],
         [0.8299, 0.0940]],

        [[0.5290, 0.1149],
         [0.3981, 0.9152]]])

In [29]:
torch.take() #将input张量看做一维返回对应索引

torch.dtype

In [32]:
a = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
torch.take(a, torch.tensor([0, 2, 5]))

tensor([1, 3, 6])

In [56]:
x= torch.tensor([[1, 2],[3, 4]])
x.tile((2, 1))

tensor([[1, 2],
        [3, 4],
        [1, 2],
        [3, 4]])

### 随机种子

In [57]:
torch.manual_seed(seed)

NameError: name 'seed' is not defined

In [60]:
torch.normal(0, 1, size=(1, 4))

tensor([[ 1.5079, -1.6458,  0.7549,  0.5332]])

In [61]:
torch.rand(3, 4)

tensor([[0.5429, 0.0493, 0.4188, 0.0269],
        [0.7479, 0.4615, 0.2202, 0.7472],
        [0.1194, 0.5630, 0.2279, 0.1969]])

In [64]:
torch.randint(5, 6, (2, 3))

tensor([[5, 5, 5],
        [5, 5, 5]])

In [63]:
torch.randn(3, 4)

tensor([[-0.5224,  2.3377,  0.3585, -1.4834],
        [-0.3933,  0.3714, -0.6492, -0.1244],
        [ 0.3488,  0.4573, -0.9525,  0.0361]])

In [65]:
torch.randperm(4) # 随机组合

tensor([1, 3, 2, 0])